# Generated by Django 3.0.6 on 2020-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('emobile', models.BigIntegerField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
